### ISSUE TITLE
KeyError: 'translatedText'

### ISSUE THREAD

**Issue by BigZapper** [Beomi/pypapago#2]
I have this problem:
Traceback (most recent call last):
  File "sub.py", line 1624, in <module>
    result = translator.translate(i.content, source='en', target='vi',)
  File "C:\Python38\lib\site-packages\pypapago\translator.py", line 60, in translate
    return response.json()['translatedText']
KeyError: 'translatedText'

How to fix it?

**Comment by MineEric64** [comment]
please write translator.py on line 59:

```
if not verbose:
            if 'translatedText' in response.json():
                return response.json()['translatedText']
            else:
                return ''
```
